[package]
name = "takuzu"
version = "0.5.1"
authors = ["Letheed <dev@daweb.se>"]
description = "Takuzu (a.k.a. Binairo) number puzzle solver"
documentation = "https://docs.rs/takuzu"
repository = "https://github.com/letheed/takuzu"
readme = "README.md"
keywords = ["takuzu", "binairo", "solver", "puzzle", "binary"]
license = "MPL-2.0"

[dependencies]
libc = "0.2"

[lib]
name = "takuzu"
path = "src/lib.rs"

[[bin]]
name = "takuzu"
path = "src/main.rs"
