[package]
name = "takuzu"
version = "0.4.0"
authors = ["Letheed <dev@daweb.se>"]
description = """
A library for solving Takuzu (a.k.a. Binairo) number puzzles.
The crate also contains an implementation called `tackle`. \
"""
documentation = "https://letheed.github.io/takuzu/takuzu"
homepage = "https://github.com/Letheed/takuzu"
repository = "https://github.com/Letheed/takuzu"
readme = "README.md"
keywords = ["takuzu", "binairo", "sudoku", "puzzle", "binary"]
license = "MPL-2.0"

[dependencies]
libc = "0.2"

[lib]
name = "takuzu"
path = "src/lib.rs"

[[bin]]
name = "takuzu-solver"
path = "src/main.rs"
