[package]
name = "takuzu"
version = "0.2.0"
authors = ["Letheed <dev@daweb.se>"]
description = """
A library for solving Takuzu (a.k.a. Binairo) number puzzles.

The crate also contains an implementation called `tackle`.\
Use the library if you need integration or would rather write your own main,\
or clone the repository and run `cargo run --release FILE` for solving away a grid.\
"""
documentation = "https://letheed.github.io/takuzu"
homepage = "https://crates.io/crates/takuzu"
repository = "https://github.com/Letheed/takuzu"
readme = "README.md"
keywords = ["takuzu", "binairo", "sudoku", "puzzle", "binary"]
license = "MPL-2.0"

[dependencies]
libc = "^0.1"

[lib]
name = "takuzu"
path = "src/lib.rs"

[[bin]]
name = "tackle"
path = "src/main.rs"
